augmentationmanager:
  _target_: data.augmentations.AugmentationManager

#randomcrop:
#  _target_: data.augmentations.RandomCrop
#  p: 1.0
#  chunk_size_sec: 3
#  sr: 44100
#  window_stft: ${...featurizer.direct_transform.win_length}
#  hop_stft: ${...featurizer.direct_transform.hop_length}

gainscale:
  _target_: data.augmentations.GainScale
  p: 0.5
  min_db: -10.
  max_db: 10.

mix:
  _target_: data.augmentations.Mix
  p: 0.5
  min_db: 0.
  max_db: 5.

#flipstereo:
#  _target_: data.augmentations.FlipStereo
#  p: 0.25
#
#flippolarity:
#  _target_: data.augmentations.FlipPolarity
#  p: 0.25

#pitchshift:
#  _target_: data.augmentations.PitchShift
#  p: 0.75
#  sample_rate: 44100
#  min_semitone: -2
#  max_semitone: 2


