# defaults
defaults:
  - model: band_split_rope_transformer
  - train_dataset: default
  - val_dataset: default
  - test_dataset: default
  - sad: default
  - augmentations: default
  - featurizer: stft
  - callbacks: default
  - _self_

# data
train_loader:
  batch_size: 1
  num_workers: 8
  shuffle: True
  drop_last: True
val_loader:
  batch_size: 1
  num_workers: 8
  shuffle: False
  drop_last: False

# optimization
opt:
  _target_: torch.optim.AdamW
  lr: 5e-4
# sch:
#   _target_: torch.optim.lr_scheduler.StepLR
#   step_size: 40000
#   gamma: 0.98

# torch.optim.lr_scheduler.LambdaLR
sch:
    warmup_step: 5
    alpha: 0.1
    step_size: 40000
    gamma: 0.999

ckpt_path: null

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: "/tb_logs"
  name: ""
  version: ""
  default_hp_metric: False

trainer:
  fast_dev_run: False
  max_epochs: 250
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 5
  log_every_n_steps: 100
  accelerator: "auto"
  devices: 8
  gradient_clip_val: 5
  precision: 32
  enable_progress_bar: True
  benchmark: True
  deterministic: False

# hydra
experiment_dirname: band-split-rope-transformer
hydra:
  run:
    dir: logs/${...experiment_dirname}/${now:%Y-%m-%d}_${now:%H-%M}
  job:
    chdir: False
