model:
  sr: 44100
  n_fft: 2048
  bandsplits:
    - [ 1000, 100 ]
    - [ 4000, 250 ]
    - [ 8000, 500 ]
    - [ 16000, 1000 ]
    - [ 20000, 2000 ]
  t_timesteps: 263
  bottleneck_layer: 'rnn'
  fc_dim: 128
  rnn_dim: 256
  rnn_type: "LSTM"
  bidirectional: True
  num_layers: 12
  mlp_dim: 512
  return_mask: False

  complex_as_channel: True
  is_mono: False

featurizer:
  direct_transform:
    _target_: torchaudio.transforms.Spectrogram
    n_fft: 2048
    win_length: 2048
    hop_length: 512
    power: null

  inverse_transform:
    _target_: torchaudio.transforms.InverseSpectrogram
    n_fft: 2048
    win_length: 2048
    hop_length: 512

audio_params:
  target: 'vocals'
  is_mono: false
  sr: 44100
  win_size: 3
  hop_size: 0.5
  batch_size: 8
  # window: 'hann'
  window: null