model:
  dim: 256
  depth: 6
  time_transformer_depth: 1
  freq_transformer_depth: 1
  heads: 8
  attn_dropout: 0.1
  ff_dropout: 0.1

featurizer:
  direct_transform:
    _target_: torchaudio.transforms.Spectrogram
    n_fft: 2048
    win_length: 2048
    hop_length: 512
    power: null

  inverse_transform:
    _target_: torchaudio.transforms.InverseSpectrogram
    n_fft: 2048
    win_length: 2048
    hop_length: 512

audio_params:
  target: 'vocals'
  is_mono: false
  sr: 44100
  win_size: 3
  hop_size: 0.5
  batch_size: 8
  # window: 'hann'
  window: null